-- SORI security snapshot: function EXECUTE privileges (153 SECURITY DEFINER + 16 invoker functions in public)
-- project: tieojdbzmqcmlwyqltrk / captured at 2026-10-02 22:30:45.429761+00 (UTC) = 2026-10-03 KST
-- server: PostgreSQL 17.6 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 15.2.0, 64-bit
-- Generated read-only from catalog queries (pg_policies, pg_class.relacl, pg_proc, pg_views, storage.buckets).
-- See README.md in this folder before running anything.

-- At capture time EVERY public function had: {=X/postgres,postgres=X,anon=X,authenticated=X,service_role=X}
-- (i.e. EXECUTE for PUBLIC, anon, authenticated, service_role).
-- Section A = SECURITY DEFINER functions (what P0 M2 will revoke). Section B = SECURITY INVOKER functions.
-- Section C = schema default privileges for future objects (relevant if M2 runs ALTER DEFAULT PRIVILEGES).
begin;

-- ===== A. SECURITY DEFINER (153) =====
revoke all on function public.accept_program_quote_v2(uuid,uuid,text,integer,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.accept_program_quote_v2(uuid,uuid,text,integer,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.accept_program_quote(uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.accept_program_quote(uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.assert_chart_community_publishable(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.assert_chart_community_publishable(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.bind_ba_session_to_chart(uuid,uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.bind_ba_session_to_chart(uuid,uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.boost_feed_segment(text,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.boost_feed_segment(text,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.bump_community_post_comment_count() from PUBLIC, anon, authenticated, service_role; grant execute on function public.bump_community_post_comment_count() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.bump_shop_community_activity() from PUBLIC, anon, authenticated, service_role; grant execute on function public.bump_shop_community_activity() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.can_view_community_post_full(text,uuid,uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.can_view_community_post_full(text,uuid,uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.can_view_community_post_full(text,uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.can_view_community_post_full(text,uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.can_view_whisper_post(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.can_view_whisper_post(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.complete_ai_tool_job(uuid,jsonb,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.complete_ai_tool_job(uuid,jsonb,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.complete_market_escrow(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.complete_market_escrow(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.complete_settlement_withdraw(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.complete_settlement_withdraw(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.convert_review_request_events(uuid,uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.convert_review_request_events(uuid,uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.count_unread_whispers() from PUBLIC, anon, authenticated, service_role; grant execute on function public.count_unread_whispers() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.create_market_listing_inquiry(uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.create_market_listing_inquiry(uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.create_mentoring_request(uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.create_mentoring_request(uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.credit_free_echo_capped(uuid,integer,text,text,uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.credit_free_echo_capped(uuid,integer,text,text,uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.credit_free_echo_customer(uuid,integer,text,text,uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.credit_free_echo_customer(uuid,integer,text,text,uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.credit_points(uuid,integer,text,text,text,uuid,uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.credit_points(uuid,integer,text,text,text,uuid,uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.credit_settlement(uuid,integer,text,text,uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.credit_settlement(uuid,integer,text,text,uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.debit_echo_wallet(uuid,integer,text,text,uuid,text,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.debit_echo_wallet(uuid,integer,text,text,uuid,text,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.debit_points(uuid,integer,text,text,uuid,uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.debit_points(uuid,integer,text,text,uuid,uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.delete_shop_customers(uuid[]) from PUBLIC, anon, authenticated, service_role; grant execute on function public.delete_shop_customers(uuid[]) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.earn_echo_on_customer_qa_post() from PUBLIC, anon, authenticated, service_role; grant execute on function public.earn_echo_on_customer_qa_post() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.earn_echo_on_customer_review() from PUBLIC, anon, authenticated, service_role; grant execute on function public.earn_echo_on_customer_review() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.earn_echo_on_visit_checked() from PUBLIC, anon, authenticated, service_role; grant execute on function public.earn_echo_on_visit_checked() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.earn_points_on_community_content() from PUBLIC, anon, authenticated, service_role; grant execute on function public.earn_points_on_community_content() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.enroll_seminar_class(uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.enroll_seminar_class(uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.ensure_customer_wallet(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.ensure_customer_wallet(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.ensure_shop_wallet(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.ensure_shop_wallet(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.expire_mentoring_enhancement_grace() from PUBLIC, anon, authenticated, service_role; grant execute on function public.expire_mentoring_enhancement_grace() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.expire_stale_boost_placements() from PUBLIC, anon, authenticated, service_role; grant execute on function public.expire_stale_boost_placements() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.expire_stale_premium_overlays() from PUBLIC, anon, authenticated, service_role; grant execute on function public.expire_stale_premium_overlays() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.fan_boost_apply_fill(uuid,jsonb,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.fan_boost_apply_fill(uuid,jsonb,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_ai_tool_quota(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_ai_tool_quota(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_chart_bookmark_counts(uuid[]) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_chart_bookmark_counts(uuid[]) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_community_feed(text,integer,integer,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_community_feed(text,integer,integer,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_customer_wallet(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_customer_wallet(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_home_feed(integer,integer,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_home_feed(integer,integer,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_interleaved_feed_ids(text,uuid[],integer,integer,text,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_interleaved_feed_ids(text,uuid[],integer,integer,text,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_mentoring_for_chart(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_mentoring_for_chart(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_seminar_detail(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_seminar_detail(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_shop_assets(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_shop_assets(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_shop_promo_credits(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_shop_promo_credits(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_shop_sponsorship_impact(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_shop_sponsorship_impact(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_shop_supporter_header(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_shop_supporter_header(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_shop_trust_score(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_shop_trust_score(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_shop_wallet(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_shop_wallet(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_supporter_interaction_statement(uuid,uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_supporter_interaction_statement(uuid,uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.grant_staff_role(uuid,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.grant_staff_role(uuid,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.grant_tier_upgrade_reward(uuid,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.grant_tier_upgrade_reward(uuid,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.handle_new_user() from PUBLIC, anon, authenticated, service_role; grant execute on function public.handle_new_user() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.has_staff_role(text[]) from PUBLIC, anon, authenticated, service_role; grant execute on function public.has_staff_role(text[]) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.hide_community_post(uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.hide_community_post(uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.hold_market_escrow(uuid,uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.hold_market_escrow(uuid,uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.insert_review_request_event(uuid,uuid,text,uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.insert_review_request_event(uuid,uuid,text,uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_active_boost_placements(integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_active_boost_placements(integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_active_premium_overlays(integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_active_premium_overlays(integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_boost_candidates_scored(text,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_boost_candidates_scored(text,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_boost_gift_impact_reports_for_customer(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_boost_gift_impact_reports_for_customer(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_boost_gift_impact_reports(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_boost_gift_impact_reports(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_community_posts_safe(text,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_community_posts_safe(text,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_discover_directors(integer,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_discover_directors(integer,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_fan_boost_supporters_batch(text,uuid[],integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_fan_boost_supporters_batch(text,uuid[],integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_fan_boost_supporters(text,uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_fan_boost_supporters(text,uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_following_feed(integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_following_feed(integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_market_listings_scored(text,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_market_listings_scored(text,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_my_boost_gifts_for_customer(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_my_boost_gifts_for_customer(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_my_boost_gifts(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_my_boost_gifts(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_my_case_bookmark_ids(integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_my_case_bookmark_ids(integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_my_region_content_bookmarks(integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_my_region_content_bookmarks(integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_my_subscriptions(integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_my_subscriptions(integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_my_whispers(text,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_my_whispers(text,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_pending_supporter_notifications(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_pending_supporter_notifications(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_review_request_events(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_review_request_events(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_shop_supporters(uuid,text,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_shop_supporters(uuid,text,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.list_unified_community_feed(text,integer,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.list_unified_community_feed(text,integer,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.mark_best_community_comment(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.mark_best_community_comment(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.mark_review_request_reminded(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.mark_review_request_reminded(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.mark_whisper_read(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.mark_whisper_read(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.merge_shop_customers(uuid,uuid[],jsonb) from PUBLIC, anon, authenticated, service_role; grant execute on function public.merge_shop_customers(uuid,uuid[],jsonb) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.pick_boost_slot_targets(text,integer,text,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.pick_boost_slot_targets(text,integer,text,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.preview_whisper_audience(uuid,text,text[],uuid[],uuid[],integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.preview_whisper_audience(uuid,text,text[],uuid[],uuid[],integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.program_customer_coupon_counts(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.program_customer_coupon_counts(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.program_expire_coupons(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.program_expire_coupons(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.program_shop_is_director(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.program_shop_is_director(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.program_sweep_quotes(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.program_sweep_quotes(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.program_sync_quote_paid() from PUBLIC, anon, authenticated, service_role; grant execute on function public.program_sync_quote_paid() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.publish_mentoring_post(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.publish_mentoring_post(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_ai_tool(uuid,uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_ai_tool(uuid,uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_fan_boost(uuid,text,text,uuid,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_fan_boost(uuid,text,text,uuid,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_fan_gift(uuid,text,text,uuid,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_fan_gift(uuid,text,text,uuid,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_mentoring_unlock(uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_mentoring_unlock(uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_point_shop_item(uuid,text,text,uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_point_shop_item(uuid,text,text,uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_sori_points_customer(uuid,integer,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_sori_points_customer(uuid,integer,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_sori_points(uuid,integer,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_sori_points(uuid,integer,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_special_gift(uuid,text,text,uuid,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_special_gift(uuid,text,text,uuid,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.purchase_special_supporter_gift(uuid,text,text,uuid,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.purchase_special_supporter_gift(uuid,text,text,uuid,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.queue_fan_boost_edge_fill(uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.queue_fan_boost_edge_fill(uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.record_affiliate_conversion(uuid,integer,text,integer,uuid,uuid,uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.record_affiliate_conversion(uuid,integer,text,integer,uuid,uuid,uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.record_chart_view(uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.record_chart_view(uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.refresh_market_listing_trust(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.refresh_market_listing_trust(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.refresh_seminar_feedback_report(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.refresh_seminar_feedback_report(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.refresh_shop_tier_badge(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.refresh_shop_tier_badge(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.refund_market_escrow(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.refund_market_escrow(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.request_seminar_interest(uuid,uuid,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.request_seminar_interest(uuid,uuid,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.request_settlement_withdraw(uuid,integer,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.request_settlement_withdraw(uuid,integer,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.require_staff(text[]) from PUBLIC, anon, authenticated, service_role; grant execute on function public.require_staff(text[]) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.resolve_whisper_audience_users(uuid,uuid,text,text[],uuid[],uuid[],integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.resolve_whisper_audience_users(uuid,uuid,text,text[],uuid[],uuid[],integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.respond_mentoring_request(uuid,boolean) from PUBLIC, anon, authenticated, service_role; grant execute on function public.respond_mentoring_request(uuid,boolean) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.review_grand_director_tiers() from PUBLIC, anon, authenticated, service_role; grant execute on function public.review_grand_director_tiers() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.run_fan_boost_ai_fill(uuid,uuid,uuid,text,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.run_fan_boost_ai_fill(uuid,uuid,uuid,text,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.save_chart_and_publish_case(uuid,uuid,boolean,text,text,text[],uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.save_chart_and_publish_case(uuid,uuid,boolean,text,text,text[],uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.send_thank_you_whisper(uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.send_thank_you_whisper(uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.send_whisper_post(text,text,text[],uuid[],uuid[],uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.send_whisper_post(text,text,text[],uuid[],uuid[],uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.send_whisper(text,uuid,text,text[],uuid[],uuid[],integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.send_whisper(text,uuid,text,text[],uuid[],uuid[],integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.set_review_naver_publish_status(uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.set_review_naver_publish_status(uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.set_subscription(text,uuid,uuid,boolean,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.set_subscription(text,uuid,uuid,boolean,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.settle_affiliate_conversion(uuid,text,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.settle_affiliate_conversion(uuid,text,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.settle_seminar_enrollment(uuid,numeric) from PUBLIC, anon, authenticated, service_role; grant execute on function public.settle_seminar_enrollment(uuid,numeric) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.shop_rolling_12m_funding(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.shop_rolling_12m_funding(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.submit_mentoring_feedback(uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.submit_mentoring_feedback(uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.submit_seminar_enrollment_review(uuid,jsonb,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.submit_seminar_enrollment_review(uuid,jsonb,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sync_affiliate_conversion_commission() from PUBLIC, anon, authenticated, service_role; grant execute on function public.sync_affiliate_conversion_commission() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sync_affiliate_paid_to_settlement() from PUBLIC, anon, authenticated, service_role; grant execute on function public.sync_affiliate_paid_to_settlement() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sync_membership_tickets_for_customer(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.sync_membership_tickets_for_customer(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sync_profile_from_auth_user() from PUBLIC, anon, authenticated, service_role; grant execute on function public.sync_profile_from_auth_user() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sync_shop_menus_from_jsonb() from PUBLIC, anon, authenticated, service_role; grant execute on function public.sync_shop_menus_from_jsonb() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sync_shop_owner_membership() from PUBLIC, anon, authenticated, service_role; grant execute on function public.sync_shop_owner_membership() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sync_shop_tier_metrics(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.sync_shop_tier_metrics(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sync_subscription_to_shop_followers() from PUBLIC, anon, authenticated, service_role; grant execute on function public.sync_subscription_to_shop_followers() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.toggle_case_bookmark(uuid,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.toggle_case_bookmark(uuid,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.toggle_region_content_bookmark(text,uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.toggle_region_content_bookmark(text,uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.trg_market_listing_trust_refresh() from PUBLIC, anon, authenticated, service_role; grant execute on function public.trg_market_listing_trust_refresh() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.trg_mentoring_feedback_counts() from PUBLIC, anon, authenticated, service_role; grant execute on function public.trg_mentoring_feedback_counts() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.trg_mentoring_feedback_quality() from PUBLIC, anon, authenticated, service_role; grant execute on function public.trg_mentoring_feedback_quality() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.trg_refresh_tier_on_case_share() from PUBLIC, anon, authenticated, service_role; grant execute on function public.trg_refresh_tier_on_case_share() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.trg_seminar_class_completed_funding() from PUBLIC, anon, authenticated, service_role; grant execute on function public.trg_seminar_class_completed_funding() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.trg_shop_tier_refresh() from PUBLIC, anon, authenticated, service_role; grant execute on function public.trg_shop_tier_refresh() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.unlock_community_post_with_points(uuid,uuid,integer,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.unlock_community_post_with_points(uuid,uuid,integer,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.update_mentoring_price(uuid,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.update_mentoring_price(uuid,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.update_shop_tier_badge(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.update_shop_tier_badge(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.upsert_my_profile(text,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.upsert_my_profile(text,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.upsert_proactive_mentoring(uuid,text,text,integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.upsert_proactive_mentoring(uuid,text,text,integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.upsert_seminar_class(jsonb) from PUBLIC, anon, authenticated, service_role; grant execute on function public.upsert_seminar_class(jsonb) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.verify_b2b_partner(uuid,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.verify_b2b_partner(uuid,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.verify_shop(uuid,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.verify_shop(uuid,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.viewer_has_post_unlock(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.viewer_has_post_unlock(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.viewer_owns_shop(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.viewer_owns_shop(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.viewer_shop_id() from PUBLIC, anon, authenticated, service_role; grant execute on function public.viewer_shop_id() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.viewer_shop_tier_rank() from PUBLIC, anon, authenticated, service_role; grant execute on function public.viewer_shop_tier_rank() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.write_admin_audit(text,text,text,jsonb) from PUBLIC, anon, authenticated, service_role; grant execute on function public.write_admin_audit(text,text,text,jsonb) to PUBLIC, anon, authenticated, service_role;

-- ===== B. SECURITY INVOKER (16) =====
revoke all on function public._merge_memberships_jsonb(jsonb[]) from PUBLIC, anon, authenticated, service_role; grant execute on function public._merge_memberships_jsonb(jsonb[]) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.ai_tool_period_key(timestamp with time zone) from PUBLIC, anon, authenticated, service_role; grant execute on function public.ai_tool_period_key(timestamp with time zone) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.compute_platform_fee_pct(text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.compute_platform_fee_pct(text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.compute_shop_tier_badge(integer) from PUBLIC, anon, authenticated, service_role; grant execute on function public.compute_shop_tier_badge(integer) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.echo_period_key(text,timestamp with time zone) from PUBLIC, anon, authenticated, service_role; grant execute on function public.echo_period_key(text,timestamp with time zone) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.enforce_shop_gallery_limit() from PUBLIC, anon, authenticated, service_role; grant execute on function public.enforce_shop_gallery_limit() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.fan_boost_build_fill_copy(customer_charts,customers) from PUBLIC, anon, authenticated, service_role; grant execute on function public.fan_boost_build_fill_copy(customer_charts,customers) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.feed_seed_rank(text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.feed_seed_rank(text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.feed_viewer_seed(text,text,timestamp with time zone) from PUBLIC, anon, authenticated, service_role; grant execute on function public.feed_viewer_seed(text,text,timestamp with time zone) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.get_case_timeline_group(uuid) from PUBLIC, anon, authenticated, service_role; grant execute on function public.get_case_timeline_group(uuid) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.post_body_needs_fan_fill(text,text,text,text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.post_body_needs_fan_fill(text,text,text,text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.shop_tier_rank(text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.shop_tier_rank(text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.sku_premium_tier(text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.sku_premium_tier(text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.tier_badge_rank(text) from PUBLIC, anon, authenticated, service_role; grant execute on function public.tier_badge_rank(text) to PUBLIC, anon, authenticated, service_role;
revoke all on function public.touch_ba_capture_session() from PUBLIC, anon, authenticated, service_role; grant execute on function public.touch_ba_capture_session() to PUBLIC, anon, authenticated, service_role;
revoke all on function public.trg_mentoring_body_updated() from PUBLIC, anon, authenticated, service_role; grant execute on function public.trg_mentoring_body_updated() to PUBLIC, anon, authenticated, service_role;

-- ===== C. default privileges in schema public (captured) =====
-- for role postgres in schema public on sequences: {postgres=rwU/postgres,anon=rwU/postgres,authenticated=rwU/postgres,service_role=rwU/postgres}
alter default privileges for role postgres in schema public grant all on sequences to anon, authenticated, service_role;
-- for role postgres in schema public on functions: {postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}
alter default privileges for role postgres in schema public grant execute on functions to anon, authenticated, service_role;
-- for role postgres in schema public on tables: {postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}
alter default privileges for role postgres in schema public grant all on tables to anon, authenticated, service_role;
-- for role supabase_admin in schema public on sequences: {postgres=rwU/supabase_admin,anon=rwU/supabase_admin,authenticated=rwU/supabase_admin,service_role=rwU/supabase_admin}
-- for role supabase_admin in schema public on functions: {postgres=X/supabase_admin,anon=X/supabase_admin,authenticated=X/supabase_admin,service_role=X/supabase_admin}
-- for role supabase_admin in schema public on tables: {postgres=arwdDxtm/supabase_admin,anon=arwdDxtm/supabase_admin,authenticated=arwdDxtm/supabase_admin,service_role=arwdDxtm/supabase_admin}
-- for role postgres in schema storage on sequences: {postgres=rwU/postgres,anon=rwU/postgres,authenticated=rwU/postgres,service_role=rwU/postgres}
-- for role postgres in schema storage on functions: {postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}
-- for role postgres in schema storage on tables: {postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}
-- (supabase_admin default ACLs can only be restored by supabase_admin; listed above for reference only.)

commit;
